version: '3.3'
services:
  post_db:
    container_name: reddit-mongodb
    image: mongo:${ver_mongo}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    container_name: reddit-ui
    image: ${USERNAME}/ui:${ver_ui}
    ports:
      - ${port_ui}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    container_name: reddit-post
    image: ${USERNAME}/post:${ver_post}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    container_name: reddit-comment
    image: ${USERNAME}/comment:${ver_comment}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam: 
        driver: default
        config: 
            - subnet: 10.0.2.0/24
  front_net:
    driver: bridge
    ipam: 
        driver: default
        config: 
            - subnet: 10.0.1.0/24
